name: Publish Moodle.Net

on:
    push:
        branches:
            - developer

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 7.x

            - name: Build Moodle.Net
              run: dotnet build

            - name: Publish Moodle.Net NuGet package
              run: |
                  cd /home/runner/work/Moodle.Net/Moodle.Net/Moodle.Net
                  dotnet pack -c Release --no-build
              working-directory: /

            - name: Tag
              if: startsWith(github.ref, 'refs/heads/release/')
              run: |
                git tag "v$env:GitVersion_SemVer"
                git push origin "v$env:GitVersion_SemVer"
            - name: Release
              if: startsWith(github.ref, 'refs/heads/release/')
              uses: softprops/action-gh-release@v1
              with:
                name: v${{ env.GitVersion_SemVer }}
                prerelease: ${{ env.GitVersion_PreReleaseLabel != '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
