name: Build and Publish

on:
  push:
    branches:
      - developer

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Moodle.Net'
      
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
          
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
          
      - name: Restore dependencies
        run: nuget restore $SOLUTION.sln
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.x'
      
      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
        
      - name: Run tests
        run: dotnet test Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal
        
      - name: Create NuGet package
        run: dotnet pack Moodle.Net/Moodle.Net.csproj
        
      - name: Deploy NuGet package